apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: broker
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka


---


apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    app: kafka-1
spec:
  ports:
    - name: broker
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-1


---


apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    app: kafka-2
spec:
  ports:
    - name: broker
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-2


---


apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  labels:
    app: kafka-3
spec:
  ports:
    - name: broker
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-3



---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
  labels:
    app: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka
          image: navicore/kafka:0.10.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "1"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-1"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
  labels:
    app: kafka-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka
          image: navicore/kafka:0.10.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "2"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-2"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-3
  labels:
    app: kafka-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
        - name: kafka
          image: navicore/kafka:0.10.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "3"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-3"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data

---