apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066



---



apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  selector:
    app: spark-worker
  ports:
  - name: worker
    protocol: TCP
    port: 8081
    targetPort: 8081



---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: jhongy1994/spqrkyolo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 6066
        tty: true
        volumeMounts:
        - name: spark-hostpath-volume
          mountPath: /usr/src/app
        - name: spark-django
          mountPath: /usr/src/app/videos
      volumes:
        - name: spark-hostpath-volume
          hostPath:
            path: /run/desktop/mnt/host/c/Users/pgt04/Desktop/docker/yolo/main
            type: Directory
        - name: spark-django
          hostPath:
            path: /run/desktop/mnt/host/c/Users/pgt04/Desktop/docker/main/static/media/videos
            type: Directory


---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: jhongy1994/spqrkyolo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        tty: true



---